services:
  - type: web
    name: telegram-movie-bot
    env: python
    plan: free
    buildCommand: pip install --force-reinstall -r requirements.txt
    startCommand: python main.py

    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000